FROM node:12 as build

WORKDIR /

COPY package.json .

RUN npm install

COPY . .

FROM nginx:stable-alpine

COPY --from=build /build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]